postgres: &postgres
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['DB_CONCURRENCY'] || 10 %>
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
  username: <%= ENV['DB_USER_NAME'] %>
  password: <%= ENV['DB_PWD'] || '' %>
  timeout:  5000
  port: <%= ENV['DB_PORT'] || 5432 %>
  schema_search_path: "public,shared_extensions"
development:
  <<: *postgres
  database: <%= ENV['DB_NAME'] || 'vuejs_demo_development' %>
test:
  <<: *postgres
  database: <%= ENV['DB_NAME_TEST'] || 'vuejs_demo_test' %><%= ENV['TEST_ENV_NUMBER'] %>
staging:
  <<: *postgres
  database: <%= ENV['DB_NAME'] || 'vuejs_demo_staging' %>
production:
  <<: *postgres
  database: <%= ENV['DB_NAME'] || 'vuejs_demo_production' %>
